# Generated by Django 4.1.7 on 2023-11-24 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0003_cities'),
    ]

    operations = [
        migrations.AddField(
            model_name='cities',
            name='city_id',
            field=models.IntegerField(default=1),
        ),
    ]
